// /*
// * This Java source file was generated by the Gradle 'init' task.
// */
// package whatsappwrapped;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

// class AppTest {
// @Test
// void appHasAGreeting() {
// AppMain classUnderTest = new AppMain();
// assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
// }
// }
